<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVv6Zcrj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVv6Zcrj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVv6Zcrj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVv6Zcrj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVv6Zcrj\App_KernelDevDebugContainer([
    'container.build_hash' => 'Vv6Zcrj',
    'container.build_id' => '0a4ab09b',
    'container.build_time' => 1714660259,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVv6Zcrj');
